"""Single source of truth for PC case brand recognition and normalization."""

# Canonical brand map: UPPERCASE_KEY -> Canonical Display Name
CASE_BRAND_MAP: dict[str, str] = {
    "1STPLAYER": "1stPlayer",
    "1ST PLAYER": "1stPlayer",
    "AEROCOOL": "AeroCool",
    "ANTEC": "Antec",
    "ASUS": "ASUS",
    "BE QUIET": "be quiet!",
    "BE QUIET!": "be quiet!",
    "BEQUIET": "be quiet!",
    "BITFENIX": "BitFenix",
    "CHIEFTEC": "Chieftec",
    "COOLER MASTER": "Cooler Master",
    "COOLERMASTER": "Cooler Master",
    "CORSAIR": "Corsair",
    "COUGAR": "Cougar",
    "DARKFLASH": "darkFlash",
    "DARK FLASH": "darkFlash",
    "DEEPCOOL": "DeepCool",
    "ENDORFY": "Endorfy",
    "FRACTAL DESIGN": "Fractal Design",
    "FRACTAL": "Fractal Design",
    "GAMEMAX": "GameMax",
    "GAME MAX": "GameMax",
    "GIGABYTE": "GIGABYTE",
    "HYTE": "Hyte",
    "INTER-TECH": "Inter-Tech",
    "INTER TECH": "Inter-Tech",
    "IN WIN": "In Win",
    "INWIN": "In Win",
    "JONSBO": "Jonsbo",
    "KOLINK": "Kolink",
    "LANCOOL": "Lancool",
    "LIAN LI": "Lian Li",
    "LIAN-LI": "Lian Li",
    "LIANLI": "Lian Li",
    "MONTECH": "Montech",
    "MSI": "MSI",
    "NZXT": "NZXT",
    "PHANTEKS": "Phanteks",
    "RAIDMAX": "Raidmax",
    "RAIJINTEK": "Raijintek",
    "SEGOTEP": "Segotep",
    "SHARKOON": "Sharkoon",
    "SILVERSTONE": "SilverStone",
    "SILVER STONE": "SilverStone",
    "SPIRE": "Spire",
    "TECWARE": "Tecware",
    "THERMALTAKE": "Thermaltake",
    "XIGMATEK": "Xigmatek",
    "ZALMAN": "Zalman",
}

# Flat list sorted longest-first so multi-word brands match before substrings
CASE_BRAND_TOKENS: list[str] = sorted(CASE_BRAND_MAP.keys(), key=lambda k: -len(k))
