"""Single source of truth for CPU cooler brand recognition and normalization."""

# Canonical brand map: UPPERCASE_KEY -> Canonical Display Name
COOLER_BRAND_MAP: dict[str, str] = {
    "AKASA": "Akasa",
    "ALPHACOOL": "Alphacool",
    "ALSEYE": "ALSEYE",
    "ANTEC": "Antec",
    "ARCTIC": "Arctic",
    "ASUS": "ASUS",
    "BE QUIET": "be quiet!",
    "BE QUIET!": "be quiet!",
    "BEQUIET": "be quiet!",
    "COOLER MASTER": "Cooler Master",
    "COOLERMASTER": "Cooler Master",
    "CORSAIR": "Corsair",
    "COUGAR": "Cougar",
    "CRYORIG": "Cryorig",
    "DEEPCOOL": "DeepCool",
    "EK": "EKWB",
    "EKWB": "EKWB",
    "EK WATERBLOCKS": "EKWB",
    "ENDORFY": "Endorfy",
    "ENERMAX": "Enermax",
    "FRACTAL DESIGN": "Fractal Design",
    "FRACTAL": "Fractal Design",
    "GIGABYTE": "Gigabyte",
    "IDCOOLING": "ID-COOLING",
    "ID COOLING": "ID-COOLING",
    "ID-COOLING": "ID-COOLING",
    "LIAN LI": "Lian Li",
    "LIAN-LI": "Lian Li",
    "LIANLI": "Lian Li",
    "MONTECH": "MONTECH",
    "MSI": "MSI",
    "NOCTUA": "Noctua",
    "NZXT": "NZXT",
    "PHANTEKS": "Phanteks",
    "SCYTHE": "Scythe",
    "SILVERSTONE": "SilverStone",
    "SILVER STONE": "SilverStone",
    "THERMALRIGHT": "Thermalright",
    "THERMALTAKE": "Thermaltake",
    "XPG": "XPG",
    "ZALMAN": "Zalman",
}

# Flat list sorted longest-first so multi-word brands match before substrings
COOLER_BRAND_TOKENS: list[str] = sorted(COOLER_BRAND_MAP.keys(), key=lambda k: -len(k))
