CPU_CATEGORY_URL = "https://www.pic.bg/procesori/c/28"
GPU_CATEGORY_URL = "https://www.pic.bg/videokarti/c/29"
RAM_CATEGORY_URL = "https://www.pic.bg/ram-pameti/c/33"
MOTHERBOARD_CATEGORY_URL = "https://www.pic.bg/dynni-platki/c/80"
SSD_CATEGORY_URL = "https://www.pic.bg/ssdta/c/31"
